// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjolQ8miKWvim1k4zhNlPenEA_T9O48DQ',
    appId: '1:1058002518463:web:ac39c366f554342900e10a',
    messagingSenderId: '1058002518463',
    projectId: 'chellenge-habit-app',
    authDomain: 'chellenge-habit-app.firebaseapp.com',
    storageBucket: 'chellenge-habit-app.firebasestorage.app',
    measurementId: 'G-V40XWF99L1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRwwoPLqQOPblPufpiU0fnAdW5dxZ0gQ0',
    appId: '1:1058002518463:android:d47248c611fe865200e10a',
    messagingSenderId: '1058002518463',
    projectId: 'chellenge-habit-app',
    storageBucket: 'chellenge-habit-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApPxZKAaUC7vxmcP2nbBBRSbZpjYFhW2M',
    appId: '1:1058002518463:ios:2ed8294f3a827dae00e10a',
    messagingSenderId: '1058002518463',
    projectId: 'chellenge-habit-app',
    storageBucket: 'chellenge-habit-app.firebasestorage.app',
    androidClientId: '1058002518463-l5jann6m6aotqan99b241lk78sadkblv.apps.googleusercontent.com',
    iosClientId: '1058002518463-gmpj5fdtc3ptqe2rsfpv1fpk01kfboq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.chellengeHabitApp',
  );

}